// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsIZSBIJjUCebN1dT4iExU0vXoRVzKAc',
    appId: '1:957008649282:android:4cfabd91b1b464402061db',
    messagingSenderId: '957008649282',
    projectId: 'appui-10a6e',
    storageBucket: 'appui-10a6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYG6YsXgfMJP8hSCHxDlkr5Qs9Y3u_cyM',
    appId: '1:957008649282:ios:b1af14aefc96626a2061db',
    messagingSenderId: '957008649282',
    projectId: 'appui-10a6e',
    storageBucket: 'appui-10a6e.appspot.com',
    iosClientId: '957008649282-2ehf3uktirlmbuklpip8j1ogne0d7li4.apps.googleusercontent.com',
    iosBundleId: 'jason4813.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYG6YsXgfMJP8hSCHxDlkr5Qs9Y3u_cyM',
    appId: '1:957008649282:ios:a9fde70c16ff26602061db',
    messagingSenderId: '957008649282',
    projectId: 'appui-10a6e',
    storageBucket: 'appui-10a6e.appspot.com',
    iosClientId: '957008649282-rq4t4b6d9ecm2g29bn9sih9m3en7g24m.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.isolateExample',
  );
}
